apiVersion: v2
name: pure-k8s-plugin-service-template
description: K0rdent service template for "pure-k8s-plugin"
type: application
version: 2.7.1
appVersion: "2.7.1"
dependencies:
  - name: k0rdent-catalog
    version: 1.0.0
    repository: oci://ghcr.io/k0rdent/catalog/charts
