apiVersion: v2
name: pure-csi
description: A Helm chart to refer the official pure-csi helm chart
type: application
version: 1.2.0
appVersion: "1.2.0"
dependencies:
  - name: pure-csi
    version: 1.2.0
    repository: https://purestorage.github.io/helm-charts
