apiVersion: v2
name: gpu-operator-service-template
description: k0rdent service template for Nvidia "gpu-operator"
type: application
version: 24.9.2
appVersion: "24.2.2"
dependencies:
  - name: k0rdent-catalog
    version: 1.0.0
    repository: oci://ghcr.io/k0rdent/catalog/charts
