apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k0rdent-catalog
  labels:
    k0rdent.mirantis.com/managed: "true"
  annotations:
    helm.sh/hook: pre-install
    helm.sh/resource-policy: keep
spec:
  type: oci
  url: oci://ghcr.io/k0rdent/catalog/charts
