apiVersion: v2
name: argo-cd
description: A Helm chart to refer the official argo-cd helm chart
type: application
version: 7.8.0
appVersion: "v2.12.5"
dependencies:
  - name: argo-cd
    version: 7.8.0
    repository: https://argoproj.github.io/argo-helm
