apiVersion: v2
name: argo-cd-service-template
description: K0rdent service template for "argo-cd"
type: application
version: 7.8.0
appVersion: "v2.12.5"
dependencies:
  - name: k0rdent-catalog
    version: 1.0.0
    repository: oci://ghcr.io/k0rdent/catalog/charts
