apiVersion: v2
name: external-secrets-service-template
description: K0rdent service template for "external-secrets"
type: application
version: 0.11.0
appVersion: "0.11.0"
dependencies:
  - name: k0rdent-catalog
    version: 1.0.0
    repository: oci://ghcr.io/k0rdent/catalog/charts
