tags:
  - Observability
title: "Prometheus"
summary: From metrics to insight
logo: "https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png"
description: |
  Prometheus is an open-source systems monitoring and alerting toolkit originally built at SoundCloud.
  Since its inception in 2012, many companies and organizations have adopted Prometheus, and
  the project has a very active developer and user community.
install_code: |
  ~~~bash
  helm upgrade --install prometheus oci://ghcr.io/k0rdent/catalog/charts/kgst -n kcm-system \
    --set "helm.repository.url=https://prometheus-community.github.io/helm-charts" \
    --set "helm.charts[0].name=prometheus" \
    --set "helm.charts[0].version=27.5.1"
  ~~~
verify_code: |
  ~~~bash
  kubectl get servicetemplates -A
  # NAMESPACE    NAME                       VALID
  # kcm-system   prometheus-27-5-1          true
  ~~~
deploy_code: |
  ~~~yaml
  apiVersion: k0rdent.mirantis.com/v1alpha1
  kind: ClusterDeployment
  # kind: MultiClusterService
  ...
    serviceSpec:
      services:
        - template: prometheus-27-5-1
          name: prometheus
          namespace: prometheus
  ~~~
doc_link: https://prometheus.io/docs/introduction/overview/
