apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: istio-base-1-24-3
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: istio-base
      version: 1.24.3
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: k0rdent-catalog
