apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: dapr-1-14-4
  namespace: k0rdent
spec:
  helm:
    chartSpec:
      chart: dapr
      version: 1.14.4
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: k0rdent-catalog
