apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: nginx-ingress-f5-2-0-0
  namespace: k0rdent
spec:
  helm:
    chartSpec:
      chart: nginx-ingress-f5
      version: 2.0.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: k0rdent-catalog
