apiVersion: v2
name: dapr
description: A Helm chart to refer the official dapr helm chart
type: application
version: 1.14.4
appVersion: "1.14.4"
dependencies:
  - name: dapr
    version: 1.14.4
    repository: https://dapr.github.io/helm-charts/
  - name: dapr-dashboard
    version: 0.15.0
    repository: https://dapr.github.io/helm-charts/
