apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{ .Values.helm.repository.name | default .Release.Name }}
  labels:
    k0rdent.mirantis.com/managed: "true"
spec:
  type: {{ .Values.helm.repository.type }}
  url: {{ required "A valid 'helm.repository.url' value is required!" .Values.helm.repository.url }}
